# Generated by Django 4.2.8 on 2023-12-07 10:19

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('name', models.CharField(max_length=1024)),
                ('slug', models.SlugField(max_length=1024, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('name', models.CharField(max_length=1024)),
                ('slug', models.SlugField(max_length=1024, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_id', models.IntegerField()),
                ('facility_type', models.CharField(max_length=255)),
                ('cnn', models.IntegerField()),
                ('location_description', models.TextField(blank=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('blocklot', models.CharField(blank=True, max_length=20)),
                ('block', models.CharField(blank=True, max_length=20)),
                ('lot', models.CharField(blank=True, max_length=20)),
                ('permit', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(blank=True, max_length=20)),
                ('food_items', models.TextField(blank=True)),
                ('x', models.DecimalField(blank=True, decimal_places=8, max_digits=16, null=True)),
                ('y', models.DecimalField(blank=True, decimal_places=8, max_digits=16, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('schedule', models.TextField(blank=True)),
                ('days_hours', models.TextField(blank=True)),
                ('noi_sent', models.CharField(blank=True, max_length=20)),
                ('approved', models.DateTimeField(blank=True, null=True)),
                ('received', models.DateField(blank=True, null=True)),
                ('prior_permit', models.IntegerField(default=0)),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
                ('fire_prevention_districts', models.IntegerField(blank=True, null=True)),
                ('police_districts', models.IntegerField(blank=True, null=True)),
                ('supervisor_districts', models.IntegerField(blank=True, null=True)),
                ('zip_codes', models.IntegerField(blank=True, null=True)),
                ('neighborhoods', models.IntegerField(blank=True, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trucks.applicant')),
            ],
            options={
                'ordering': ['location_id'],
            },
        ),
        migrations.CreateModel(
            name='TruckFoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trucks.fooditem')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trucks.truck')),
            ],
        ),
        migrations.AddConstraint(
            model_name='truckfooditem',
            constraint=models.UniqueConstraint(fields=('truck', 'food_item'), name='truck_food_item_unique'),
        ),
    ]
