version: '3'

services:
  db:
    image: postgis/postgis:16-3.4
    ports:
      - "15432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
