version: '3'

services:
  db:
    image: postgis/postgis:16-3.4
    ports:
      - "15432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  app:
    build:
      dockerfile: ./Dockerfile
      context: .
    volumes:
      - ./:/app/
    ports:
      - "8000:8000"
    environment:
      DJANGO_SETTINGS_MODULE: config.settings
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      DB_PORT: 5432
